// <auto-generated />
using System;
using Ecosologic.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecosologic.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EcosologicDbContext))]
    [Migration("20260903173412_AddSolarCommercialNonEmptyChecks")]
    partial class AddSolarCommercialNonEmptyChecks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.CrmNotificationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueDay")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LeadId")
                        .IsUnique()
                        .HasFilter("\"TaskId\" IS NULL");

                    b.HasIndex("TaskId")
                        .IsUnique()
                        .HasFilter("\"TaskId\" IS NOT NULL");

                    b.HasIndex("ReadAt", "DueAt");

                    b.ToTable("crm_notifications", (string)null);
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.HomeContentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("HeroImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HeroText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("HeroTitle")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("ProcessStepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SolutionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("home_content", (string)null);
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.LeadActivityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LeadId");

                    b.ToTable("lead_activities", (string)null);
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.LeadRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("ReminderAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("WonAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.LeadTaskRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DueAt");

                    b.HasIndex("LeadId");

                    b.ToTable("lead_tasks", (string)null);
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.ProposalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("QuoteId");

                    b.ToTable("proposals", null, t =>
                        {
                            t.HasCheckConstraint("CK_proposals_generated_requires_file", "(\"Status\" <> 'Generated') OR (\"FileUrl\" IS NOT NULL AND \"FileUrl\" <> '')");

                            t.HasCheckConstraint("CK_proposals_status", "\"Status\" IN ('Draft','Generated','Sent','Accepted','Rejected','Expired')");
                        });
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.SolarQuoteRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MarginPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<Guid>("SizingId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("TaxPercent")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SizingId");

                    b.ToTable("solar_quotes", null, t =>
                        {
                            t.HasCheckConstraint("CK_solar_quotes_approved_requires_snapshot", "(\"Status\" <> 'Approved') OR (\"SnapshotJson\" IS NOT NULL AND \"SnapshotJson\" <> '')");

                            t.HasCheckConstraint("CK_solar_quotes_margin_percent_nonnegative", "\"MarginPercent\" >= 0");

                            t.HasCheckConstraint("CK_solar_quotes_status", "\"Status\" IN ('Draft','Approved','Sent','Accepted','Rejected','Expired')");

                            t.HasCheckConstraint("CK_solar_quotes_tax_percent_nonnegative", "\"TaxPercent\" >= 0");

                            t.HasCheckConstraint("CK_solar_quotes_total_cost_nonnegative", "\"TotalCost\" >= 0");

                            t.HasCheckConstraint("CK_solar_quotes_total_price_nonnegative", "\"TotalPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.SolarSizingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Concessionaria")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Grupo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResultsJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("LeadId");

                    b.ToTable("solar_sizings", null, t =>
                        {
                            t.HasCheckConstraint("CK_solar_sizings_grupo_nonempty", "\"Grupo\" <> ''");

                            t.HasCheckConstraint("CK_solar_sizings_modalidade_nonempty", "\"Modalidade\" <> ''");

                            t.HasCheckConstraint("CK_solar_sizings_results_for_calculated_approved", "(\"Status\" NOT IN ('Calculated','Approved')) OR (\"ResultsJson\" IS NOT NULL AND \"ResultsJson\" <> '')");

                            t.HasCheckConstraint("CK_solar_sizings_status", "\"Status\" IN ('Draft','Calculated','Approved','Cancelled')");
                        });
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.CrmNotificationRecord", b =>
                {
                    b.HasOne("Ecosologic.Infrastructure.Persistence.LeadRecord", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecosologic.Infrastructure.Persistence.LeadTaskRecord", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.LeadActivityRecord", b =>
                {
                    b.HasOne("Ecosologic.Infrastructure.Persistence.LeadRecord", "Lead")
                        .WithMany("Activities")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.LeadTaskRecord", b =>
                {
                    b.HasOne("Ecosologic.Infrastructure.Persistence.LeadRecord", "Lead")
                        .WithMany("Tasks")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.ProposalRecord", b =>
                {
                    b.HasOne("Ecosologic.Infrastructure.Persistence.SolarQuoteRecord", "Quote")
                        .WithMany("Proposals")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.SolarQuoteRecord", b =>
                {
                    b.HasOne("Ecosologic.Infrastructure.Persistence.SolarSizingRecord", "Sizing")
                        .WithMany("Quotes")
                        .HasForeignKey("SizingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sizing");
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.SolarSizingRecord", b =>
                {
                    b.HasOne("Ecosologic.Infrastructure.Persistence.LeadRecord", null)
                        .WithMany()
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.LeadRecord", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.SolarQuoteRecord", b =>
                {
                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("Ecosologic.Infrastructure.Persistence.SolarSizingRecord", b =>
                {
                    b.Navigation("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
